set_property SRC_FILE_INFO {cfile:/home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_clk_wiz_0_0/uc_system_clk_wiz_0_0.xdc rfile:../../../../../lab2.srcs/sources_1/bd/uc_system/ip/uc_system_clk_wiz_0_0/uc_system_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:uc_system_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/izoomko/wrk/4grade/io/lab3/lab2.srcs/constrs_1/new/constraints.xdc rfile:../../../../../lab2.srcs/constrs_1/new/constraints.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/izoomko/wrk/4grade/io/lab3/lab2.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_microblaze_0_0/uc_system_microblaze_0_0.xdc rfile:../../../../../lab2.srcs/sources_1/bd/uc_system/ip/uc_system_microblaze_0_0/uc_system_microblaze_0_0.xdc id:4 order:EARLY scoped_inst:uc_system_i/microblaze_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_axi_timer_0_0/uc_system_axi_timer_0_0.xdc rfile:../../../../../lab2.srcs/sources_1/bd/uc_system/ip/uc_system_axi_timer_0_0/uc_system_axi_timer_0_0.xdc id:5 order:EARLY scoped_inst:uc_system_i/axi_timer_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_dlmb_v10_0/uc_system_dlmb_v10_0.xdc rfile:../../../../../lab2.srcs/sources_1/bd/uc_system/ip/uc_system_dlmb_v10_0/uc_system_dlmb_v10_0.xdc id:6 order:EARLY scoped_inst:uc_system_i/microblaze_0_local_memory/dlmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_ilmb_v10_0/uc_system_ilmb_v10_0.xdc rfile:../../../../../lab2.srcs/sources_1/bd/uc_system/ip/uc_system_ilmb_v10_0/uc_system_ilmb_v10_0.xdc id:7 order:EARLY scoped_inst:uc_system_i/microblaze_0_local_memory/ilmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_axi_uartlite_0_0/uc_system_axi_uartlite_0_0.xdc rfile:../../../../../lab2.srcs/sources_1/bd/uc_system/ip/uc_system_axi_uartlite_0_0/uc_system_axi_uartlite_0_0.xdc id:8 order:EARLY scoped_inst:uc_system_i/axi_uartlite_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_proc_sys_reset_0_0/uc_system_proc_sys_reset_0_0.xdc rfile:../../../../../lab2.srcs/sources_1/bd/uc_system/ip/uc_system_proc_sys_reset_0_0/uc_system_proc_sys_reset_0_0.xdc id:9 order:EARLY scoped_inst:uc_system_i/proc_sys_reset_0/U0} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PHASESHIFT_MODE WAVEFORM [get_cells uc_system_i/clk_wiz_0/inst/mmcm_adv_inst]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[15]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[14]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[13]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[12]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[11]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[10]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[9]}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[8]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[7]}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[6]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[5]}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[4]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[3]}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[2]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[1]}]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[0]}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clock_rtl]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports pwm0]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0/U0]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/clk_wiz_0/inst]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/axi_timer_0/U0]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/axi_gpio_0/U0]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_local_memory/dlmb_v10/U0]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_local_memory/ilmb_v10/U0]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/axi_uartlite_0/U0]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/proc_sys_reset_0/U0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/BRAMInterconnect_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/IC_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/Timer_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/Timer_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/axi_bram_ctrl_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/axi_gpio_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/axi_timer_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/axi_uartlite_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/clk_wiz_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_axi_periph/m03_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_axi_periph/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_local_memory/dlmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_local_memory/ilmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/microblaze_0_local_memory/lmb_bram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells uc_system_i/proc_sys_reset_0]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins uc_system_i/microblaze_0/U0/Reset]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clock_rtl [get_ports clock_rtl]
set_property src_info {type:SCOPED_XDC file:5 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list uc_system_i/axi_timer_0/U0/TC_CORE_I/TIMER_CONTROL_I/INPUT_DOUBLE_REGS/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D uc_system_i/axi_timer_0/U0/TC_CORE_I/TIMER_CONTROL_I/INPUT_DOUBLE_REGS2/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D uc_system_i/axi_timer_0/U0/TC_CORE_I/TIMER_CONTROL_I/INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins uc_system_i/microblaze_0_local_memory/dlmb_v10/U0/SYS_Rst]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins uc_system_i/microblaze_0_local_memory/ilmb_v10/U0/SYS_Rst]
set_property src_info {type:SCOPED_XDC file:8 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins uc_system_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]
set_property src_info {type:SCOPED_XDC file:9 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list uc_system_i/proc_sys_reset_0/U0/EXT_LPF/ACTIVE_HIGH_EXT.ACT_HI_EXT/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D uc_system_i/proc_sys_reset_0/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkfbout_uc_system_clk_wiz_0_0 -source [get_pins uc_system_i/clk_wiz_0/inst/mmcm_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock clock_rtl [get_pins uc_system_i/clk_wiz_0/inst/mmcm_adv_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_out1_uc_system_clk_wiz_0_0 -source [get_pins uc_system_i/clk_wiz_0/inst/mmcm_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock clock_rtl [get_pins uc_system_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]
