# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-19679-sirius/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/9c7f
    /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/7e3a/hdl
  } {
      /home/izoomko/Soft/xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/izoomko/Soft/xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/9c7f
    /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/7e3a/hdl
  } {
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/new/BRAMInterconnect.v
      /home/izoomko/wrk/4grade/io/lab3/hls/lab3/solution/syn/verilog/Timer_on_clock.v
      /home/izoomko/wrk/4grade/io/lab3/hls/lab3/solution/syn/verilog/Timer.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/new/EdgeDetector.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/new/Prescaler.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/new/IC.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/hdl/uc_system_wrapper.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_clk_wiz_0_0/uc_system_clk_wiz_0_0_clk_wiz.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_clk_wiz_0_0/uc_system_clk_wiz_0_0.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/55c0/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/95b9/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/f582/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_xbar_1/synth/uc_system_xbar_1.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_BRAMInterconnect_0_0/synth/uc_system_BRAMInterconnect_0_0.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_Timer_0_0/synth/uc_system_Timer_0_0.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_Timer_1_0/synth/uc_system_Timer_1_0.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_IC_0_0/synth/uc_system_IC_0_0.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/hdl/uc_system.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/f0ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_auto_pc_0/synth/uc_system_auto_pc_0.v
    }
      rt::read_vhdl -lib microblaze_v10_0_3 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/fe06/hdl/microblaze_v10_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_microblaze_0_0/synth/uc_system_microblaze_0_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_axi_timer_0_0/synth/uc_system_axi_timer_0_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_axi_gpio_0_0/synth/uc_system_axi_gpio_0_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_dlmb_v10_0/synth/uc_system_dlmb_v10_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_ilmb_v10_0/synth/uc_system_ilmb_v10_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_dlmb_bram_if_cntlr_0/synth/uc_system_dlmb_bram_if_cntlr_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_ilmb_bram_if_cntlr_0/synth/uc_system_ilmb_bram_if_cntlr_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_lmb_bram_0/synth/uc_system_lmb_bram_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_axi_bram_ctrl_0_0/synth/uc_system_axi_bram_ctrl_0_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_axi_uartlite_0_0/synth/uc_system_axi_uartlite_0_0.vhd
      /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ip/uc_system_proc_sys_reset_0_0/synth/uc_system_proc_sys_reset_0_0.vhd
    }
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_2 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_timer_v2_0_15 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/a004/hdl/axi_timer_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/e956/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_15 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/cb07/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_3_6 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/4158/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_1_4 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/ebc2/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      rt::read_vhdl -lib lmb_v10_v3_0_9 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/162e/hdl/lmb_v10_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_bram_if_cntlr_v4_0_12 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/51e1/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_bram_ctrl_v4_0_11 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/9183/hdl/axi_bram_ctrl_v4_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_uartlite_v2_0_17 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/1b8b/hdl/axi_uartlite_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_11 /home/izoomko/wrk/4grade/io/lab3/lab2.srcs/sources_1/bd/uc_system/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xpm /home/izoomko/Soft/xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-19679-sirius/realtime/uc_system_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top uc_system_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/izoomko/wrk/4grade/io/lab3/lab2.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-19679-sirius/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
