// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Timer_HH_
#define _Timer_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Timer_on_clock.h"

namespace ap_rtl {

struct Timer : public sc_module {
    // Port declarations 8
    sc_in_clk clk_i;
    sc_in< sc_logic > rst_i;
    sc_in< sc_logic > en_i;
    sc_in< sc_lv<13> > addr_bi;
    sc_in< sc_lv<32> > data_bi;
    sc_in< sc_lv<4> > we_bi;
    sc_out< sc_lv<16> > data_bo;
    sc_in< sc_logic > ap_rst;


    // Module declarations
    Timer(sc_module_name name);
    SC_HAS_PROCESS(Timer);

    ~Timer();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Timer_on_clock* StgValue_16_Timer_on_clock_fu_66;
    sc_signal< sc_lv<1> > Timer_ssdm_thread_load_fu_90_p1;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_lv<16> > StgValue_16_Timer_on_clock_fu_66_data_bo;
    sc_signal< sc_logic > StgValue_16_Timer_on_clock_fu_66_data_bo_ap_vld;
    sc_signal< sc_lv<32> > StgValue_16_Timer_on_clock_fu_66_Timer_m_tmr_V_o;
    sc_signal< sc_logic > StgValue_16_Timer_on_clock_fu_66_Timer_m_tmr_V_o_ap_vld;
    sc_signal< sc_lv<32> > StgValue_16_Timer_on_clock_fu_66_Timer_m_tval_V_o;
    sc_signal< sc_logic > StgValue_16_Timer_on_clock_fu_66_Timer_m_tval_V_o_ap_vld;
    sc_signal< sc_lv<32> > StgValue_16_Timer_on_clock_fu_66_Timer_m_tconf_V_o;
    sc_signal< sc_logic > StgValue_16_Timer_on_clock_fu_66_Timer_m_tconf_V_o_ap_vld;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > Timer_m_tmr_V;
    sc_signal< sc_lv<32> > Timer_m_tval_V;
    sc_signal< sc_lv<32> > Timer_m_tconf_V;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_Timer_m_tconf_V();
    void thread_Timer_m_tmr_V();
    void thread_Timer_m_tval_V();
    void thread_data_bo();
    void thread_Timer_ssdm_thread_load_fu_90_p1();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state2();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
