// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Timer,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.294000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=314,HLS_SYN_LUT=282}" *)

module Timer (
        clk_i,
        rst_i,
        en_i,
        addr_bi,
        data_bi,
        we_bi,
        data_bo,
        ap_rst
);


input   clk_i;
input   rst_i;
input   en_i;
input  [12:0] addr_bi;
input  [31:0] data_bi;
input  [3:0] we_bi;
output  [15:0] data_bo;
input   ap_rst;

reg[15:0] data_bo;

wire   [0:0] Timer_ssdm_thread_load_fu_90_p1;
wire   [1:0] ap_CS_fsm;
wire   [15:0] StgValue_16_Timer_on_clock_fu_66_data_bo;
wire    StgValue_16_Timer_on_clock_fu_66_data_bo_ap_vld;
wire   [31:0] StgValue_16_Timer_on_clock_fu_66_Timer_m_tmr_V_o;
wire    StgValue_16_Timer_on_clock_fu_66_Timer_m_tmr_V_o_ap_vld;
wire   [31:0] StgValue_16_Timer_on_clock_fu_66_Timer_m_tval_V_o;
wire    StgValue_16_Timer_on_clock_fu_66_Timer_m_tval_V_o_ap_vld;
wire   [31:0] StgValue_16_Timer_on_clock_fu_66_Timer_m_tconf_V_o;
wire    StgValue_16_Timer_on_clock_fu_66_Timer_m_tconf_V_o_ap_vld;
wire    ap_CS_fsm_state2;
reg   [31:0] Timer_m_tmr_V;
reg   [31:0] Timer_m_tval_V;
reg   [31:0] Timer_m_tconf_V;

Timer_on_clock StgValue_16_Timer_on_clock_fu_66(
    .ap_clk(clk_i),
    .ap_rst(ap_rst),
    .rst_i(rst_i),
    .en_i(en_i),
    .addr_bi(addr_bi),
    .data_bi(data_bi),
    .data_bo(StgValue_16_Timer_on_clock_fu_66_data_bo),
    .data_bo_ap_vld(StgValue_16_Timer_on_clock_fu_66_data_bo_ap_vld),
    .Timer_m_tmr_V_i(Timer_m_tmr_V),
    .Timer_m_tmr_V_o(StgValue_16_Timer_on_clock_fu_66_Timer_m_tmr_V_o),
    .Timer_m_tmr_V_o_ap_vld(StgValue_16_Timer_on_clock_fu_66_Timer_m_tmr_V_o_ap_vld),
    .Timer_m_tval_V_i(Timer_m_tval_V),
    .Timer_m_tval_V_o(StgValue_16_Timer_on_clock_fu_66_Timer_m_tval_V_o),
    .Timer_m_tval_V_o_ap_vld(StgValue_16_Timer_on_clock_fu_66_Timer_m_tval_V_o_ap_vld),
    .Timer_m_tconf_V_i(Timer_m_tconf_V),
    .Timer_m_tconf_V_o(StgValue_16_Timer_on_clock_fu_66_Timer_m_tconf_V_o),
    .Timer_m_tconf_V_o_ap_vld(StgValue_16_Timer_on_clock_fu_66_Timer_m_tconf_V_o_ap_vld)
);

always @ (posedge clk_i) begin
    if ((1'b1 == StgValue_16_Timer_on_clock_fu_66_Timer_m_tconf_V_o_ap_vld)) begin
        Timer_m_tconf_V <= StgValue_16_Timer_on_clock_fu_66_Timer_m_tconf_V_o;
    end
end

always @ (posedge clk_i) begin
    if ((1'b1 == StgValue_16_Timer_on_clock_fu_66_Timer_m_tmr_V_o_ap_vld)) begin
        Timer_m_tmr_V <= StgValue_16_Timer_on_clock_fu_66_Timer_m_tmr_V_o;
    end
end

always @ (posedge clk_i) begin
    if ((1'b1 == StgValue_16_Timer_on_clock_fu_66_Timer_m_tval_V_o_ap_vld)) begin
        Timer_m_tval_V <= StgValue_16_Timer_on_clock_fu_66_Timer_m_tval_V_o;
    end
end

always @ (posedge clk_i) begin
    if ((1'b1 == StgValue_16_Timer_on_clock_fu_66_data_bo_ap_vld)) begin
        data_bo <= StgValue_16_Timer_on_clock_fu_66_data_bo;
    end
end

assign Timer_ssdm_thread_load_fu_90_p1 = 1'd0;

assign ap_CS_fsm = 2'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

endmodule //Timer
